# -*- coding: utf-8 -*-
"""Python_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJLf-VrB_Ow34kLBi_gqznAemZEaT5MZ

**1.What is Python?**
    It is an high-level,interpreted,interactive and object oriented programming language.
    ->Python was developed by
"""

#To print all the key words present in python
import keyword
print(keyword.kwlist)
a=len(keyword.kwlist)
print(a)

"""**HOW TO USE COMMENTS PYTON ?**
 1.Single Line comment
  #Enter the comment
 2.Multi-Line comment
  '''Enter the multi line comment'''


"""

#It is an single line comment
print("Welcome to Python")


"""
hi
hello
welcome
This is an multi line comment
"""
print("These are python Basics")

"""**PYTHON VARIABLES**"""

a=10 #Declaring the variable and its value
b=30 #Declaring another variable and its value
c=a+b #A third variable has declared to print the sum of first and second variables
print("The sum is",c)

#On Strings
x="Welcome to python"
print(x)

"""**PYTHON DATA STRUCTURES**

1.LISTS
"""

#Creating a list
a=[1,2,3,4,5]
print(a)

#Creating a list with constructor()
x=([3,4,5,7,8])
y=(["India","Chaina","America"])
print(x)
print(y)

#To find what type of variable that we declared
type(a)
type(x)
type(y)

#Creating a list with both Strings and integers
x=(["India",3,4,5])
print(x)

#Create list using range function:
x=list(range(0,10))
print(x)

#Creating a list without constructor
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
print(a)

#accessing list items with index values
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
a[5]

#accessing list items with index negetive values
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
a[-3]

#Scaling of list
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
a[2:6]

#Scaling of list with Step size:
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
a[0:8:2]#Here 2 will skip 2 months for every iteration

"""**LIST BUILT-IN FUNCTIONS**"""

#To print tyhe length of the of the list
a=["January","February","March","April","May","June","July","August","September","October","November","December"]
print(len(a))

#To print the maximum value in the list
x=[1,3,4,6,8,9,12,13,45]
print(max(x))

#To print the minimum value in the list
x=[1,3,4,6,8,9,12,13,45]
print(min(x))

#To print the sum of values in the list
x=[1,3,4,6,8,9,12,13,45]
print(sum(x))

#To shuffle the numbers in the list randomly
import random #Importing random module
x=[1,3,4,6,8,9,12,13,45]
random.shuffle(x)
print(x)

"""**LIST OPERATORS**"""

#Example for + operator
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c) #It conactenates two lists

#Example for * operator
a=[1,2,3]
b=5*a
print(b) #It replicates the elements in lists

#Using of IN operatror
days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
'wednesday' in days

#Using IS operator
a="India"
b="India"
a is b

#Using IS operator
a="India"
b="china"
a is b

#Usind delete operator
days=['monday','tuesday','wednesday','thursday','friday','saturday','sunday']
print(days)
del[days[3]]
print(days)

"""**LIST METHODS**"""

#Append method
#Helps to join numbers or letters to the list
a=['a','b','c','d']
print(a)
a.append('e')
print(a)

#clear method
#Helps to clear the list
a=['a','b','c','d']
print(a)
a.clear()
print(a)

#count method
#helps to count how many times the number or letter is repeated
a=['a','b','c','d']
print(a)
a.count(b)

#copy method
#copies the sames list and prints
a=['a','b','c','d']
print(a)
b=a.copy()
print(a)

#Extend method
#Joins 2 lists
x=[1,2,3,4,5]
y=[6,7,8,9,10]
x.extend(y)
print(x)

"""**TUPLES**"""

#Creating a Tuple
a=(1,2,3,4)
print(a)
print(type(a))

#Creating a tuple with integers
a=(1,2,3,4)
print(a)

#Creating a Tuple with Float Numbers
a=(1.4,3.6,4.5,9.6)
print(a)

#Creating Tuples with Strings
a=("India","China","Vietnam")
print(a)

#Creating Multiple Data Types
a=("India",10,2.5)
print(a)

"""**PYTHON DIRECTORY**"""

#create a dictionary
a={
'name':'joy',
'age':23,
'education':'Engineer'
}
print(a)

len(a)

type(a)

x=a.keys()
print(x)

y=a.values()
y

z=a.items()
z

"""**PYTHON SETS**"""

#Example:
set1={1,2,3,4}
print(set1)

#3duplicates not allowed
set={1,2,3,4,5,6,7,1,1}
set

len(set)

type(set)

"""**PYTHON FUNCTIONS**"""

#DEF FUNCTION
def add():
  a=2
  b=3
  sum=a+b
  return sum
add()
print(add())